### ISSUE TITLE
Produce writeup on how to make muport library more modular

### ISSUE THREAD

**Issue by michaelsena** [3box/muport-core-js#26]
Includes research into what the best way to do that is.

**Comment by michaelsena** [comment]
Ideas for things to modularize: separate key management functionality from other things, making it less dependent on specific ethereum smart contracts, etc... cc @christianlundkvist

**Comment by oed** [comment]
https://docs.google.com/document/d/11pK-ltINbwxAOyGyhwNmPfdEZgVCyb79LLqQnxAZOnw/edit?ts=5c0afdfa#heading=h.g37fmaka6qcv

**Comment by oed** [comment]
This is basically done. Closing
