### ISSUE TITLE
Simple way to see if an address has a profile set 

### ISSUE THREAD

**Issue by dazuck** [3box/muport-core-js#29]
As a developer, I want to check whether an address has a profile set and when it was last updated. 

Spec'ing the need as separate from the getprofiles() call in more detail with partners.

**Comment by oed** [comment]
@dazuck please move this issue to the 3Box repo.

**Comment by dazuck** [comment]
Issue moved to [3box/3box #459](https://github.com/3box/3box/issues/459) via [**ZenHub**](https://www.zenhub.com/)
